  name: db

  services:
    mysql57:
      build:
        context: .
        dockerfile: Dockerfile.mysql57
      image: mysql:5.7
      container_name: mysql57
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL57_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL57_DATABASE}
        MYSQL_USER: ${MYSQL57_USER}
        MYSQL_PASSWORD: ${MYSQL57_PASSWORD}
        MYSQL_ROOT_HOST: "%"
      ports:
        - "${MYSQL57_PORT}:3306"
      volumes:
        - mysql57_data:/var/lib/mysql

    mysql8:
      build:
        context: .
        dockerfile: Dockerfile.mysql8
      image: mysql:8
      container_name: mysql8
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL8_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL8_DATABASE}
        MYSQL_USER: ${MYSQL8_USER}
        MYSQL_PASSWORD: ${MYSQL8_PASSWORD}
        MYSQL_ROOT_HOST: "%"
      ports:
        - "${MYSQL8_PORT}:3306"
      volumes:
        - mysql8_data:/var/lib/mysql

    mariadb10:
      build:
        context: .
        dockerfile: Dockerfile.mariadb10
      image: mariadb:10
      container_name: mariadb10
      environment:
        MYSQL_ROOT_PASSWORD: ${MARIADB10_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MARIADB10_DATABASE}
        MYSQL_USER: ${MARIADB10_USER}
        MYSQL_PASSWORD: ${MARIADB10_PASSWORD}
      ports:
        - "${MARIADB10_PORT}:3306"
      volumes:
        - mariadb10_data:/var/lib/mysql

    mariadb11:
      build:
        context: .
        dockerfile: Dockerfile.mariadb11
      image: mariadb:11
      container_name: mariadb11
      environment:
        MYSQL_ROOT_PASSWORD: ${MARIADB11_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MARIADB11_DATABASE}
        MYSQL_USER: ${MARIADB11_USER}
        MYSQL_PASSWORD: ${MARIADB11_PASSWORD}
      ports:
        - "${MARIADB11_PORT}:3306"
      volumes:
        - mariadb11_data:/var/lib/mysql

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        PMA_ARBITRARY: 1
      ports:
        - "${PHPMYADMIN_PORT}:80"
      depends_on:
        - mysql57
        - mysql8
        - mariadb10
        - mariadb11

    postgres:
      build:
        context: .
        dockerfile: Dockerfile.postgresql
      image: postgres:latest
      container_name: postgres
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "${POSTGRES_PORT}:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      ports:
        - "${PGADMIN_PORT}:80"
      volumes:
        - ./pgadmin/servers.json:/pgadmin4/servers.json
      depends_on:
        - postgres

    php:
      image: php:8.2-fpm
      container_name: php
      volumes:
        - ./src:/var/www/html
        - ./php-config/php.ini:/usr/local/etc/php/php.ini
      depends_on:
        - mysql57
        - mysql8


    nginx:
      image: nginx:alpine
      container_name: nginx
      ports:
        - "${NGINX_PORT}:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./src:/var/www/html
      depends_on:
        - php

  volumes:
    mysql57_data:
    mysql8_data:
    mariadb10_data:
    mariadb11_data:
    postgres_data:
